// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbujwalvdcjefepwnyky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5idWp3YWx2ZGNqZWZlcHdueWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTgwODAsImV4cCI6MjA2NjQzNDA4MH0.KWv1To6ZzSjoZrEpMWFunpA6iL78vhqJb4p6G7eUi8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);